//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _20230515_1_TelefonRehberi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kisi
    {
        public int KisiId { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public string Telefon { get; set; }
        public string EMail { get; set; }
        public int KullaniciId { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
    }
}
